// import { Filament, FilamentStatus } from './types';

// export const mockFilaments: Filament[] = [
//   {
//     id: '1',
//     brand: 'Prusament',
//     name: 'Galaxy Black',
//     material: 'PLA',
//     colorName: '#232323',
//     colorHex: '#232323',
//     weightTotal: 1000,
//     weightRemaining: 850,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAkMmaljGSDQhK_SdN4MkArAJ1wMYBUY4d1B8ejd6A2TP8iQ8nfopxnvFod3RLIXq5mWjTOD4zDUp-ZAg37IaMZGATnWTqUQBG9bNCSwF6rc1T35UsMvGnAzNsxapiTinMoofJLj8wwIpyfZ2LBZLZOvfI_9RQ6Wc7WjIYZGGpXAv54QfRTPXqvJZXhrRSS1dc_tzNe6Ha-XtP5ndC_K_JgGCL4jB5lgK7QWP5deVmAbmRCn-xPNPNlzbNr3v2fWhUmROjzHhMDtsZr',
//     status: FilamentStatus.Adequate,
//   },
//   {
//     id: '2',
//     brand: 'eSUN',
//     name: 'Fire Red',
//     material: 'PETG',
//     colorName: '#EF4444',
//     colorHex: '#EF4444',
//     weightTotal: 1000,
//     weightRemaining: 120,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMC0XkP7gHq7O1RF438-yii5Ug71w8v_zuOdjmtuqqV3ZCLdwjDzrsOlXb54NJdifW8FOH_4fMhWhDcRgSjwg-asT8Gwuy6mFl4BurK_z0AdXjkUD9p-trblTmCNs7wt85JD16GWvdvJ51lJOVIakN8_jIKMDP0zoN2Ul4BpdwpTtb64OuP_OSSQ5ZwEtHf6QhB9wXFLUoYKXuBHl4LlVXiQiWGnjWfJqbpC2jutez5yogwndnsxgOcCRLYj2Hh4DBZZTjj__hwjWM',
//     status: FilamentStatus.LowStock,
//   },
//   {
//     id: '3',
//     brand: 'Polymaker',
//     name: 'Azure Blue',
//     material: 'ABS',
//     colorName: '#3B82F6',
//     colorHex: '#3B82F6',
//     weightTotal: 1000,
//     weightRemaining: 550,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaIPRiHnGnP7xhxpEMF1vViYkaUCQK7byFmLzydYMf9nOJTbUwXd1J8np956rP_W4Gh591hCHtxqVCDwKq1-E7osH078DnXHwJtlE43GfjqpmqpVEzvtnVVs9F9Gy6_4kEYA6iyDC40NBzZklBut74d_fXe97T9Y2vT6bdhUy7WE1286EkmSo6czJMUM6q8pLzpcDLVEUExqKBM8pGAyO1M8W3Ih_fKb5b23WP4JXuDrapDy04-TYZ0-yXku-ztN7l-cIb5ZTUvp0G',
//     status: FilamentStatus.Adequate,
//   },
//   {
//     id: '4',
//     brand: 'Generic',
//     name: 'Matte White',
//     material: 'PLA',
//     colorName: '#F8FAFC',
//     colorHex: '#F8FAFC',
//     weightTotal: 1000,
//     weightRemaining: 980,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAoHQVo7ExEdxB2Xgut9ppYI7C478pk5m3oM68A1SGjVf7_LYvSmzqtapxhV1417xDrhUR_kSlWfILUpJ8ufFcuciRnuxHoznwGgBT4LCBTdJASCOzyTMhYKW-vzcJU05sIcjr9BGAlR1g1B4FEQ5b9Wne6XJKLmLT5gX4ANjYQ2ZkipJWRANH5BkNrdVOrlMhRVWdO5n_3nEUu3pSgWkdHoDZv6j58q-TEXzFBfy4xZbtrdoVTp9L_UKbMihf9E8sSnV--R4B7l4Sz',
//     status: FilamentStatus.Adequate,
//   },
//   {
//     id: '5',
//     brand: 'Overture',
//     name: 'Silk Gold',
//     material: 'PLA',
//     colorName: '#FFD700',
//     colorHex: '#FFD700',
//     weightTotal: 1000,
//     weightRemaining: 320,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCoiHNV5X4sdwu2RpR7sRZh_iJj14xkNGnsc6nJ-CNtTi8FcxMSHGfE4FzGDboOjlVMt0F1Z7UJGGeOOa3h4JzlxwIhkT7_Ud_J0xFCPIKv9QHE3wzsjD9bzaF6wyQLFnEie91BREuq-iNaWpYBKj_NDB90doXMpSbQHDhWBaVxuW3rJWDVQPcWZOR0cZbWWWRJjcayI05L10bvwWnCZ6tZdvJi7YuPIqoGlHYXWPyPmrJ7dvEEvLmVkEvHhstwA_TEZkvW6W2e3K13',
//     status: FilamentStatus.Adequate,
//   },
//   {
//     id: '6',
//     brand: 'NinjaTek',
//     name: 'Neon Green',
//     material: 'TPU',
//     colorName: '#39FF14',
//     colorHex: '#39FF14',
//     weightTotal: 1000,
//     weightRemaining: 750,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAy93F9_s_NVuZwYRc4QcsHn06Ttd6SyN-Xo-8s9TRbvJDiwHElpSPbqGOX8mXxcQo-R1LkQNTAet-tZTu0EFrX3j8Ng1IAwVOmFv2r1Y1TcfOyxJQNGcenmlacDF24olkkZAwgqi1df55LefsTbxpEpbiV9djuklsjfqP9DxLsSJF52t8zJIS-z67Yxqbmvlu3nAVOFIMqxPY9FosbyvnCfNc87nh6T62OTzvgLfcDQvgx6SqOdPSv03Ap6VoX4AaCyDy2utNu4LCd',
//     status: FilamentStatus.Adequate,
//   },
//   {
//     id: '7',
//     brand: 'Overture',
//     name: 'Matte Red',
//     material: 'PLA',
//     colorName: '#D32F2F',
//     colorHex: '#D32F2F',
//     weightTotal: 1000,
//     weightRemaining: 50,
//     imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoCixJxfPZVyUgdW_JbudohxTW0P-P-9uEjFbnE7DkQbuSEATUS0RNMfUCsfWnAy_ja0rKkB2TV7_rc4PD4RY6m6EtOXgGb1QhfP1Gq7Yx6zMw8YMXyibg2ogU9YWvS7rcDzHqvJhGihwoR1U1dxgZBR1PuDH1axgD37WzU604PVXBpuLBAYcoBlOtXdmEnN7MMKVxwqsz6vKIrk1C4zzCId0WJhkTZ1XXxsYtmR3ZHt7ohfb6CtSzvW4M-gn0B37gRlVLxYvNdcfJ',
//     status: FilamentStatus.Critical,
//   }
// ];